version: "3"

services:
  nextjs:
    container_name: nextjs
    build:
      context: .. # root of the project
      dockerfile: docker/next/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: database
    build:
      context: ..
      dockerfile: docker/mysql/Dockerfile
    image: custom-mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
